create table candidates.candidates(
    id uuid default gen_random_uuid() primary key,
    txn_date timestamp default now(),
    name text,
    email_id text,
    password text,
    mobile text,
    profile_photo uuid references candidates.profile_photos(id),
    country text references locations.countries(tag),
    state text references locations.states(tag),
    district text references locations.districts(tag),
    current_address text,
    profile_summary text,
    work_experience uuid references candidates.work_experience(id),
    personal_projects uuid references candidates.personal_projects(id),
    education uuid references candidates.education(id),
    achievements text,
    skills jsonb[],
    languages jsonb[],
    interest text[],
    website_links text[],
    certificates uuid references candidates.certificates(id),
    organizations uuid references candidates.organizations(id)
);